apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-worker
  labels:
    app: notifications-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-worker
  template:
    metadata:
      labels:
        app: notifications-worker
    spec:
      containers:
        - name: notifications-worker
          image: fcg-notifications-api:latest
          imagePullPolicy: Never
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: notifications-worker-config
            - secretRef:
                name: notifications-worker-secret
          env:
            - name: DOTNET_ENVIRONMENT
              value: "Production"
      restartPolicy: Always
