// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace FCG.Notifications.Tests.BDD.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PaymentProcessedNotificationFeature : object, global::Xunit.IClassFixture<PaymentProcessedNotificationFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "BDD/Features", "PaymentProcessed Notification", "  As the system\r\n  When a payment is processed\r\n  The appropriate email notificat" +
                "ion should be sent based on the payment outcome", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PaymentProcessedNotification.feature"
#line hidden
        
        public PaymentProcessedNotificationFeature(PaymentProcessedNotificationFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("BDD/Features/PaymentProcessedNotification.feature", "Feature: PaymentProcessed Notification\n  As the system\n  When a payment is proces" +
                    "sed\n  The appropriate email notification should be sent based on the payment out" +
                    "come\n\n  Scenario: Purchase confirmation sent when payment is approved\n    Given " +
                    "a payment for game \"God of War\" to email \"player@fcg.com\" with amount 199.90 was" +
                    " approved\n    When the PaymentProcessed event is consumed\n    Then SendPurchaseC" +
                    "onfirmationAsync should be called once\n    And it should be called with email \"p" +
                    "layer@fcg.com\" and game \"God of War\" and amount 199.90\n\n  Scenario: Purchase rej" +
                    "ection sent when payment is rejected\n    Given a payment for game \"Cyberpunk 207" +
                    "7\" to email \"gamer@fcg.com\" was rejected with reason \"Insufficient funds (simula" +
                    "ted)\"\n    When the PaymentProcessed event is consumed\n    Then SendPurchaseRejec" +
                    "tedAsync should be called once\n    And it should be called with email \"gamer@fcg" +
                    ".com\" and game \"Cyberpunk 2077\" and reason \"Insufficient funds (simulated)\"\n\n  S" +
                    "cenario: Confirmation is not sent when payment is rejected\n    Given a payment f" +
                    "or game \"The Witcher 3\" to email \"fan@fcg.com\" was rejected with reason \"Insuffi" +
                    "cient funds (simulated)\"\n    When the PaymentProcessed event is consumed\n    The" +
                    "n SendPurchaseConfirmationAsync should not be called\n\n  Scenario: Rejection is n" +
                    "ot sent when payment is approved\n    Given a payment for game \"Elden Ring\" to em" +
                    "ail \"soulsplayer@fcg.com\" with amount 299.90 was approved\n    When the PaymentPr" +
                    "ocessed event is consumed\n    Then SendPurchaseRejectedAsync should not be calle" +
                    "d\n", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("BDD/Features/PaymentProcessedNotification.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "PaymentProcessed Notification", "  As the system\r\n  When a payment is processed\r\n  The appropriate email notificat" +
                        "ion should be sent based on the payment outcome", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Purchase confirmation sent when payment is approved", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a payment for game \"God of War\" to email \"player@fcg.com\" with amount 199.90 was " +
                                                            "approved", null, null, "a7fe552f240b635dbd902f4cddec3dda"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "the PaymentProcessed event is consumed", null, null, "3a209a1bb329d3539895fcca7933b29b"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "SendPurchaseConfirmationAsync should be called once", null, null, "9f0e3b1d1119b158a8ce01757c9677fc"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "it should be called with email \"player@fcg.com\" and game \"God of War\" and amount " +
                                                            "199.90", null, null, "9a25aaf12691d357ab9e2f2d0a8aad0a")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "4f84800a49e35c5092214488d5f55556")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Purchase rejection sent when payment is rejected", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a payment for game \"Cyberpunk 2077\" to email \"gamer@fcg.com\" was rejected with re" +
                                                            "ason \"Insufficient funds (simulated)\"", null, null, "48105a0799d5865087377b9b3d642d14"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "the PaymentProcessed event is consumed", null, null, "40f5d08bad54365384d68a174e563f29"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "SendPurchaseRejectedAsync should be called once", null, null, "895c52b0548aa558ad3ac78f351f5f52"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "it should be called with email \"gamer@fcg.com\" and game \"Cyberpunk 2077\" and reas" +
                                                            "on \"Insufficient funds (simulated)\"", null, null, "a4d30301e8fc345c82fe52e2dfe18f55")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "4d02c8d1142f875eac2be2ed0cc8689c")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Confirmation is not sent when payment is rejected", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a payment for game \"The Witcher 3\" to email \"fan@fcg.com\" was rejected with reaso" +
                                                            "n \"Insufficient funds (simulated)\"", null, null, "9a229ecca229cb5fa79246ddc0476616"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "the PaymentProcessed event is consumed", null, null, "1fb7384bf651ab5e978afa77e214ea69"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "SendPurchaseConfirmationAsync should not be called", null, null, "e03eb8ef4661ad5b8a04439dc37ef2e1")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "8383efc9e343c2528345fecd2f9e392e")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Rejection is not sent when payment is approved", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a payment for game \"Elden Ring\" to email \"soulsplayer@fcg.com\" with amount 299.90" +
                                                            " was approved", null, null, "ae2eda8563ab5558b4bb703084101e3a"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "the PaymentProcessed event is consumed", null, null, "bf27af9b0ba1125caf2b1e167d3e093b"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "SendPurchaseRejectedAsync should not be called", null, null, "b202c8c30a4f975683b4c3f3ea86a96d")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "12cef9f37d82305b89bc5652dfe4d16e"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("d1a28ac30cc67556b2d3a5f1a736f83a", "BDD/Features/PaymentProcessedNotification.feature", "Purchase confirmation sent when payment is approved", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a7fe552f240b635dbd902f4cddec3dda"}), "ad2e3a2b80852156bb3f90cd878463e8", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a payment for game \"God of War\" to email \"player@fcg.com\" with amount 199.90 was " +
                                                "approved"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3a209a1bb329d3539895fcca7933b29b"}), "417e92eedbd1c051b0aef5cc84e8235e", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the PaymentProcessed event is consumed"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9f0e3b1d1119b158a8ce01757c9677fc"}), "53bf701bc848635a993f30514d0ad351", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "SendPurchaseConfirmationAsync should be called once"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9a25aaf12691d357ab9e2f2d0a8aad0a"}), "912ae171c591fd5499970af4dede240a", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "it should be called with email \"player@fcg.com\" and game \"God of War\" and amount " +
                                                "199.90")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "4f84800a49e35c5092214488d5f55556"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("3fe80be7d26c4955885b9023b5945398", "BDD/Features/PaymentProcessedNotification.feature", "Purchase rejection sent when payment is rejected", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "48105a0799d5865087377b9b3d642d14"}), "2d64078689c8d55b8e038f88aaf403e2", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a payment for game \"Cyberpunk 2077\" to email \"gamer@fcg.com\" was rejected with re" +
                                                "ason \"Insufficient funds (simulated)\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "40f5d08bad54365384d68a174e563f29"}), "8b84e3b65dde56579cae028129867cbc", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the PaymentProcessed event is consumed"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "895c52b0548aa558ad3ac78f351f5f52"}), "816698542681f753bdeda787740e4e4b", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "SendPurchaseRejectedAsync should be called once"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a4d30301e8fc345c82fe52e2dfe18f55"}), "ba3aa35c6be06d5cb8d86ebb2ddc7da3", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "it should be called with email \"gamer@fcg.com\" and game \"Cyberpunk 2077\" and reas" +
                                                "on \"Insufficient funds (simulated)\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "4d02c8d1142f875eac2be2ed0cc8689c"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("d9d7c32ae622b155a1347354b5fbd747", "BDD/Features/PaymentProcessedNotification.feature", "Confirmation is not sent when payment is rejected", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "9a229ecca229cb5fa79246ddc0476616"}), "ea9c90ece49ae65b8e511af469b94785", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a payment for game \"The Witcher 3\" to email \"fan@fcg.com\" was rejected with reaso" +
                                                "n \"Insufficient funds (simulated)\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "1fb7384bf651ab5e978afa77e214ea69"}), "2226e424de1d0d5b921b992ccb807dc3", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the PaymentProcessed event is consumed"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e03eb8ef4661ad5b8a04439dc37ef2e1"}), "062fcc6f90134257a64ebbad92fb8220", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "SendPurchaseConfirmationAsync should not be called")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "8383efc9e343c2528345fecd2f9e392e"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("7e14f3df857f185b9aea10e2dbf1850c", "BDD/Features/PaymentProcessedNotification.feature", "Rejection is not sent when payment is approved", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ae2eda8563ab5558b4bb703084101e3a"}), "8e11d3cb3c9aa95c9c98696607db8205", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a payment for game \"Elden Ring\" to email \"soulsplayer@fcg.com\" with amount 299.90" +
                                                " was approved"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "bf27af9b0ba1125caf2b1e167d3e093b"}), "36e7f9e4ae426159956c70426f210a28", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the PaymentProcessed event is consumed"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b202c8c30a4f975683b4c3f3ea86a96d"}), "1f6aa9da0dc40853b751a1f4ed7d46c8", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "SendPurchaseRejectedAsync should not be called")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "12cef9f37d82305b89bc5652dfe4d16e"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(PaymentProcessedNotificationFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(PaymentProcessedNotificationFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(PaymentProcessedNotificationFeature.PicklesFunc));
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Purchase confirmation sent when payment is approved")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentProcessed Notification")]
        [global::Xunit.TraitAttribute("Description", "Purchase confirmation sent when payment is approved")]
        public async global::System.Threading.Tasks.Task PurchaseConfirmationSentWhenPaymentIsApproved()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Purchase confirmation sent when payment is approved", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await testRunner.GivenAsync("a payment for game \"God of War\" to email \"player@fcg.com\" with amount 199.90 was " +
                        "approved", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.WhenAsync("the PaymentProcessed event is consumed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
    await testRunner.ThenAsync("SendPurchaseConfirmationAsync should be called once", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 10
    await testRunner.AndAsync("it should be called with email \"player@fcg.com\" and game \"God of War\" and amount " +
                        "199.90", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Purchase rejection sent when payment is rejected")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentProcessed Notification")]
        [global::Xunit.TraitAttribute("Description", "Purchase rejection sent when payment is rejected")]
        public async global::System.Threading.Tasks.Task PurchaseRejectionSentWhenPaymentIsRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Purchase rejection sent when payment is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 13
    await testRunner.GivenAsync("a payment for game \"Cyberpunk 2077\" to email \"gamer@fcg.com\" was rejected with re" +
                        "ason \"Insufficient funds (simulated)\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 14
    await testRunner.WhenAsync("the PaymentProcessed event is consumed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
    await testRunner.ThenAsync("SendPurchaseRejectedAsync should be called once", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 16
    await testRunner.AndAsync("it should be called with email \"gamer@fcg.com\" and game \"Cyberpunk 2077\" and reas" +
                        "on \"Insufficient funds (simulated)\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Confirmation is not sent when payment is rejected")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentProcessed Notification")]
        [global::Xunit.TraitAttribute("Description", "Confirmation is not sent when payment is rejected")]
        public async global::System.Threading.Tasks.Task ConfirmationIsNotSentWhenPaymentIsRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Confirmation is not sent when payment is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 18
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
    await testRunner.GivenAsync("a payment for game \"The Witcher 3\" to email \"fan@fcg.com\" was rejected with reaso" +
                        "n \"Insufficient funds (simulated)\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 20
    await testRunner.WhenAsync("the PaymentProcessed event is consumed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 21
    await testRunner.ThenAsync("SendPurchaseConfirmationAsync should not be called", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Rejection is not sent when payment is approved")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentProcessed Notification")]
        [global::Xunit.TraitAttribute("Description", "Rejection is not sent when payment is approved")]
        public async global::System.Threading.Tasks.Task RejectionIsNotSentWhenPaymentIsApproved()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Rejection is not sent when payment is approved", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 23
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 24
    await testRunner.GivenAsync("a payment for game \"Elden Ring\" to email \"soulsplayer@fcg.com\" with amount 299.90" +
                        " was approved", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 25
    await testRunner.WhenAsync("the PaymentProcessed event is consumed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 26
    await testRunner.ThenAsync("SendPurchaseRejectedAsync should not be called", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await PaymentProcessedNotificationFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await PaymentProcessedNotificationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
