// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace FCG.Notifications.Tests.BDD.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class PaymentProcessedNotificationFeature : object, global::Xunit.IClassFixture<PaymentProcessedNotificationFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "BDD/Features", "PaymentProcessed Notification", "  As the system\r\n  When a payment is processed\r\n  The appropriate email notificat" +
                "ion should be sent based on the payment outcome", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "PaymentProcessedNotification.feature"
#line hidden
        
        public PaymentProcessedNotificationFeature(PaymentProcessedNotificationFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("BDD/Features/PaymentProcessedNotification.feature", "Feature: PaymentProcessed Notification\r\n  As the system\r\n  When a payment is proc" +
                    "essed\r\n  The appropriate email notification should be sent based on the payment " +
                    "outcome\r\n\r\n  Scenario: Purchase confirmation sent when payment is approved\r\n    " +
                    "Given a payment for game \"God of War\" to email \"player@fcg.com\" with amount 199." +
                    "90 was approved\r\n    When the PaymentProcessed event is consumed\r\n    Then SendP" +
                    "urchaseConfirmationAsync should be called once\r\n    And it should be called with" +
                    " email \"player@fcg.com\" and game \"God of War\" and amount 199.90\r\n\r\n  Scenario: P" +
                    "urchase rejection sent when payment is rejected\r\n    Given a payment for game \"C" +
                    "yberpunk 2077\" to email \"gamer@fcg.com\" was rejected with reason \"Insufficient f" +
                    "unds (simulated)\"\r\n    When the PaymentProcessed event is consumed\r\n    Then Sen" +
                    "dPurchaseRejectedAsync should be called once\r\n    And it should be called with e" +
                    "mail \"gamer@fcg.com\" and game \"Cyberpunk 2077\" and reason \"Insufficient funds (s" +
                    "imulated)\"\r\n\r\n  Scenario: Confirmation is not sent when payment is rejected\r\n   " +
                    " Given a payment for game \"The Witcher 3\" to email \"fan@fcg.com\" was rejected wi" +
                    "th reason \"Insufficient funds (simulated)\"\r\n    When the PaymentProcessed event " +
                    "is consumed\r\n    Then SendPurchaseConfirmationAsync should not be called\r\n\r\n  Sc" +
                    "enario: Rejection is not sent when payment is approved\r\n    Given a payment for " +
                    "game \"Elden Ring\" to email \"soulsplayer@fcg.com\" with amount 299.90 was approved" +
                    "\r\n    When the PaymentProcessed event is consumed\r\n    Then SendPurchaseRejected" +
                    "Async should not be called\r\n", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("BDD/Features/PaymentProcessedNotification.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "PaymentProcessed Notification", "  As the system\r\n  When a payment is processed\r\n  The appropriate email notificat" +
                        "ion should be sent based on the payment outcome", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Purchase confirmation sent when payment is approved", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a payment for game \"God of War\" to email \"player@fcg.com\" with amount 199.90 was " +
                                                            "approved", null, null, "e04c4b9d163fef5db28da63bfd4442cb"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "the PaymentProcessed event is consumed", null, null, "6aab0bf8893f875ea87c219b78d703b9"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "SendPurchaseConfirmationAsync should be called once", null, null, "3cd121dca0fb84549852e22eb1d380f1"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "it should be called with email \"player@fcg.com\" and game \"God of War\" and amount " +
                                                            "199.90", null, null, "310eb786e36c385a95f8b7e6cb7b5f48")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "df7fe9d498209059a0b6881fde6ee6fc")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Purchase rejection sent when payment is rejected", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a payment for game \"Cyberpunk 2077\" to email \"gamer@fcg.com\" was rejected with re" +
                                                            "ason \"Insufficient funds (simulated)\"", null, null, "de65d8bc7caefe5fbf1330ab679fbaf7"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "the PaymentProcessed event is consumed", null, null, "6095e12fde505356a392e6b90ecf663f"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "SendPurchaseRejectedAsync should be called once", null, null, "ab57186f626f615d8b6c68c5b1436ac6"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "it should be called with email \"gamer@fcg.com\" and game \"Cyberpunk 2077\" and reas" +
                                                            "on \"Insufficient funds (simulated)\"", null, null, "ddd865c5becc905680ee67e1813a2e53")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "a1e1979518c6bb5c90a29608a2113d8a")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Confirmation is not sent when payment is rejected", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a payment for game \"The Witcher 3\" to email \"fan@fcg.com\" was rejected with reaso" +
                                                            "n \"Insufficient funds (simulated)\"", null, null, "6d599c31fb41d153b0cf0e3d247435ca"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "the PaymentProcessed event is consumed", null, null, "6a6ae22b494fe050a606b56e03fc8df9"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "SendPurchaseConfirmationAsync should not be called", null, null, "b73076eaaf172350ae23a08481075618")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "730bf06a867a235496edbd07f9e59512")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Rejection is not sent when payment is approved", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "a payment for game \"Elden Ring\" to email \"soulsplayer@fcg.com\" with amount 299.90" +
                                                            " was approved", null, null, "f89225f4d5b91d56a5238863d63ccc36"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "the PaymentProcessed event is consumed", null, null, "e37f8ca819073b5980f7f19ccb2a5d72"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "SendPurchaseRejectedAsync should not be called", null, null, "958e5e0a1da81152823233068928dbe1")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "e682f459325e6759b4ba2b8b50720a10"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("0b83143d12cd7a5a9be19af0c990f3ac", "BDD/Features/PaymentProcessedNotification.feature", "Purchase confirmation sent when payment is approved", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e04c4b9d163fef5db28da63bfd4442cb"}), "2ce8c57325917d51b60c6e52906b0eb3", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a payment for game \"God of War\" to email \"player@fcg.com\" with amount 199.90 was " +
                                                "approved"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "6aab0bf8893f875ea87c219b78d703b9"}), "af10f9b6c5baae58b07d44be56cef3c7", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the PaymentProcessed event is consumed"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3cd121dca0fb84549852e22eb1d380f1"}), "3d92f7bd52c7745aa1dd8f1ff42fe073", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "SendPurchaseConfirmationAsync should be called once"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "310eb786e36c385a95f8b7e6cb7b5f48"}), "a6eab1712616ff5aac3f528cf602f3df", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "it should be called with email \"player@fcg.com\" and game \"God of War\" and amount " +
                                                "199.90")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "df7fe9d498209059a0b6881fde6ee6fc"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("1ef1278a02f3125b9c1e9378e09cc13e", "BDD/Features/PaymentProcessedNotification.feature", "Purchase rejection sent when payment is rejected", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "de65d8bc7caefe5fbf1330ab679fbaf7"}), "c0c474f707f0b750bc214e7feda3270f", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a payment for game \"Cyberpunk 2077\" to email \"gamer@fcg.com\" was rejected with re" +
                                                "ason \"Insufficient funds (simulated)\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "6095e12fde505356a392e6b90ecf663f"}), "5aa619c79e5e9f51b3b2711a936db08e", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the PaymentProcessed event is consumed"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ab57186f626f615d8b6c68c5b1436ac6"}), "7d5d2a2e12e6e654968e7b3fe2e5218b", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "SendPurchaseRejectedAsync should be called once"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ddd865c5becc905680ee67e1813a2e53"}), "f94eb131befb8e5da49951963269ab17", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "it should be called with email \"gamer@fcg.com\" and game \"Cyberpunk 2077\" and reas" +
                                                "on \"Insufficient funds (simulated)\"")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "a1e1979518c6bb5c90a29608a2113d8a"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("f58f4f20cb2cbc51b78e12476e498c2b", "BDD/Features/PaymentProcessedNotification.feature", "Confirmation is not sent when payment is rejected", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "6d599c31fb41d153b0cf0e3d247435ca"}), "cff4572532cad6598e8a68f1ec307669", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a payment for game \"The Witcher 3\" to email \"fan@fcg.com\" was rejected with reaso" +
                                                "n \"Insufficient funds (simulated)\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "6a6ae22b494fe050a606b56e03fc8df9"}), "5889ee5421e6d057803040f0534ff36f", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the PaymentProcessed event is consumed"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b73076eaaf172350ae23a08481075618"}), "62294445c04d57588df77783b4c29072", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "SendPurchaseConfirmationAsync should not be called")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "730bf06a867a235496edbd07f9e59512"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("374ccce031875e508f433d3de6e0d5a4", "BDD/Features/PaymentProcessedNotification.feature", "Rejection is not sent when payment is approved", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f89225f4d5b91d56a5238863d63ccc36"}), "1140cc6a1df16e5299e95d2234ed7105", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "a payment for game \"Elden Ring\" to email \"soulsplayer@fcg.com\" with amount 299.90" +
                                                " was approved"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e37f8ca819073b5980f7f19ccb2a5d72"}), "380aabc6d3c82055b5c934f3c35c14d5", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "the PaymentProcessed event is consumed"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "958e5e0a1da81152823233068928dbe1"}), "6c1d9a6d74dc5e52864c4e4897a07591", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "SendPurchaseRejectedAsync should not be called")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "e682f459325e6759b4ba2b8b50720a10"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(PaymentProcessedNotificationFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(PaymentProcessedNotificationFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(PaymentProcessedNotificationFeature.PicklesFunc));
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Purchase confirmation sent when payment is approved")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentProcessed Notification")]
        [global::Xunit.TraitAttribute("Description", "Purchase confirmation sent when payment is approved")]
        public async global::System.Threading.Tasks.Task PurchaseConfirmationSentWhenPaymentIsApproved()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Purchase confirmation sent when payment is approved", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await testRunner.GivenAsync("a payment for game \"God of War\" to email \"player@fcg.com\" with amount 199.90 was " +
                        "approved", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.WhenAsync("the PaymentProcessed event is consumed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 9
    await testRunner.ThenAsync("SendPurchaseConfirmationAsync should be called once", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 10
    await testRunner.AndAsync("it should be called with email \"player@fcg.com\" and game \"God of War\" and amount " +
                        "199.90", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Purchase rejection sent when payment is rejected")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentProcessed Notification")]
        [global::Xunit.TraitAttribute("Description", "Purchase rejection sent when payment is rejected")]
        public async global::System.Threading.Tasks.Task PurchaseRejectionSentWhenPaymentIsRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Purchase rejection sent when payment is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 13
    await testRunner.GivenAsync("a payment for game \"Cyberpunk 2077\" to email \"gamer@fcg.com\" was rejected with re" +
                        "ason \"Insufficient funds (simulated)\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 14
    await testRunner.WhenAsync("the PaymentProcessed event is consumed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
    await testRunner.ThenAsync("SendPurchaseRejectedAsync should be called once", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 16
    await testRunner.AndAsync("it should be called with email \"gamer@fcg.com\" and game \"Cyberpunk 2077\" and reas" +
                        "on \"Insufficient funds (simulated)\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Confirmation is not sent when payment is rejected")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentProcessed Notification")]
        [global::Xunit.TraitAttribute("Description", "Confirmation is not sent when payment is rejected")]
        public async global::System.Threading.Tasks.Task ConfirmationIsNotSentWhenPaymentIsRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Confirmation is not sent when payment is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 18
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
    await testRunner.GivenAsync("a payment for game \"The Witcher 3\" to email \"fan@fcg.com\" was rejected with reaso" +
                        "n \"Insufficient funds (simulated)\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 20
    await testRunner.WhenAsync("the PaymentProcessed event is consumed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 21
    await testRunner.ThenAsync("SendPurchaseConfirmationAsync should not be called", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Rejection is not sent when payment is approved")]
        [global::Xunit.TraitAttribute("FeatureTitle", "PaymentProcessed Notification")]
        [global::Xunit.TraitAttribute("Description", "Rejection is not sent when payment is approved")]
        public async global::System.Threading.Tasks.Task RejectionIsNotSentWhenPaymentIsApproved()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Rejection is not sent when payment is approved", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 23
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 24
    await testRunner.GivenAsync("a payment for game \"Elden Ring\" to email \"soulsplayer@fcg.com\" with amount 299.90" +
                        " was approved", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 25
    await testRunner.WhenAsync("the PaymentProcessed event is consumed", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 26
    await testRunner.ThenAsync("SendPurchaseRejectedAsync should not be called", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await PaymentProcessedNotificationFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await PaymentProcessedNotificationFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
